[project]
name = "douglas"
version = "0.1.0"
description = "AI-assisted development loop orchestrator"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Douglas Contributors" }]
license = { text = "MIT" }
dependencies = ["typer>=0.9", "pyyaml>=6.0"]

[project.scripts]
douglas = "douglas.cli:app"

[project.optional-dependencies]
dev = ["pytest", "ruff", "black", "isort", "mypy"]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
