# Generated by Douglas for $project_name

# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$$py.class

# Virtual environments
.venv/
venv/
ENV/

# Distribution / packaging
build/
dist/
*.egg-info/

# Unit test / coverage reports
htmlcov/
.coverage
.coverage.*
.cache
.pytest_cache/

# Douglas artifacts
ai-inbox/
douglas_review.md
